apiVersion: v1
kind: Service
metadata:
  name: springboot-kubernetes
spec:
  selector:
    app: springboot-kubernetes
  ports:
    - protocol: "TCP"
      port: 8080 #Cluster port
      targetPort: 8080 #Exposed Port
  type: NodePort

